import { IExam } from "./interface";

export const availableExams: IExam[] = [
  {
    id: "1",
    title: "Civil Engineering",
    courseCode: "CE101",
    date: "12 Mar 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
    isRegistered: false,
  },
  {
    id: "2",
    title: "Cyber Security",
    courseCode: "CS101",
    date: "12 Mar 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
  },
  {
    id: "3",
    title: "Basic Physics",
    courseCode: "PHY101",
    date: "14 Apr 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
  },
  {
    id: "4",
    title: "Mathematics",
    courseCode: "MAT101",
    date: "12 Mar 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
  },
  {
    id: "5",
    title: "Accounting",
    courseCode: "Acct101",
    date: "22 May 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
  },
  {
    id: "6",
    title: "Computer Studies",
    courseCode: "Comp101",
    date: "22 May 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
  },
  {
    id: "7",
    title: "Robotics",
    courseCode: "RB101",
    date: "22 May 2025",
    registrationDeadline: "5 Mar 2025",
    fee: "N2,000",
    status: "UPCOMING",
  },
];
