import { IDBExamQuestion } from '@/src/lib/db/interface';
import { ExamQuestionTypeEnum } from '@/src/lib/enums';

export const questions: IDBExamQuestion[] = [
	{
		id: '1',
		type: ExamQuestionTypeEnum.MCQ,
		questionText: 'What is the valency of oxygen',
		options: [
			{ displayOrder: 1, id: '1', optionText: '1' },
			{ displayOrder: 2, id: '2', optionText: '2' },
			{ displayOrder: 3, id: '3', optionText: '3' },
			{ displayOrder: 4, id: '4', optionText: '4' },
		],
		attemptId: '222',
		displayOrder: 1,
		examId: '111',
		marks: 2,
	},
	{
		id: '2',
		type: ExamQuestionTypeEnum.MCQ,
		questionText: 'What is the chemical formula for table salt?',
		options: [
			{ displayOrder: 1, id: '1', optionText: 'KCL' },
			{ displayOrder: 2, id: '2', optionText: 'NaCL' },
			{ displayOrder: 3, id: '3', optionText: 'CaCl₂' },
			{ displayOrder: 4, id: '4', optionText: 'MgCl₂' },
		],
		attemptId: '222',
		displayOrder: 2,
		examId: '111',
		marks: 2,
	},
	{
		id: '3',
		type: ExamQuestionTypeEnum.MCQ,
		questionText: 'What is the chemical symbol for Sodium?',
		options: [
			{ displayOrder: 2, id: '1', optionText: 'So' },
			{ displayOrder: 4, id: '2', optionText: 'Na' },
			{ displayOrder: 3, id: '3', optionText: 'Sd' },
			{ displayOrder: 1, id: '4', optionText: 'Sn' },
		],
		attemptId: '222',
		displayOrder: 3,
		examId: '111',
		marks: 2,
	},
	{
		id: '4',
		type: 'SHORT',
		questionText: 'Explain the process of oxidation in your own words.',
		attemptId: '222',
		displayOrder: 4,
		examId: '111',
		marks: 6,
	},
	{
		id: '5',
		type: 'SHORT',
		questionText: 'Describe the differences between Ionic and Covalent bonds.',
		attemptId: '222',
		displayOrder: 5,
		examId: '111',
		marks: 6,
	},
	{
		id: '9',
		type: 'SHORT',
		questionText: 'Explain the process of oxidation in your own words.',
		attemptId: '222',
		displayOrder: 6,
		examId: '111',
		marks: 6,
	},
	{
		id: '10',
		type: 'SHORT',
		questionText: 'Describe the differences between Ionic and Covalent bonds.',
		attemptId: '222',
		displayOrder: 7,
		examId: '111',
		marks: 6,
	},
];
