'use client';

import {
	BookOpen,
	Search,
	Filter,
	FolderOpen,
	AlertCircle,
	School,
	Users,
	Calendar,
	Clock,
	FileText,
	MessageCircle,
	CreditCard,
	Building2,
	Package,
	ShoppingBag,
	UserPlus,
	Mail,
	Phone,
	MapPin,
	Globe,
	Lock,
	Unlock,
	CheckCircle,
	XCircle,
	RefreshCw,
	PlusCircle,
	Download,
	Upload,
	Settings,
	HelpCircle,
	Star,
	Heart,
	Bell,
	Eye,
	EyeOff,
	Trash2,
	Edit2,
	Copy,
	Share2,
	Printer,
	Save,
	Send,
	Inbox,
	Archive,
	Flag,
	MoreHorizontal,
	Clipboard,
} from 'lucide-react';
import { EmptyStateIcon } from './interface';

export const iconMap: Record<EmptyStateIcon, React.ComponentType<any>> = {
	book: BookOpen,
	search: Search,
	filter: Filter,
	folder: FolderOpen,
	alert: AlertCircle,
	school: School,
	clipboard: Clipboard,
	users: Users,
	calendar: Calendar,
	clock: Clock,
	file: FileText,
	message: MessageCircle,
	'credit-card': CreditCard,
	building: Building2,
	package: Package,
	shopping: ShoppingBag,
	'user-plus': UserPlus,
	mail: Mail,
	phone: Phone,
	map: MapPin,
	globe: Globe,
	lock: Lock,
	unlock: Unlock,
	check: CheckCircle,
	x: XCircle,
	refresh: RefreshCw,
	plus: PlusCircle,
	download: Download,
	upload: Upload,
	settings: Settings,
	help: HelpCircle,
	star: Star,
	heart: Heart,
	bell: Bell,
	eye: Eye,
	'eye-off': EyeOff,
	trash: Trash2,
	edit: Edit2,
	copy: Copy,
	share: Share2,
	printer: Printer,
	save: Save,
	send: Send,
	inbox: Inbox,
	archive: Archive,
	flag: Flag,
	more: MoreHorizontal,
};

export const sizeConfig = {
	sm: {
		container: 'py-8 px-4',
		icon: 'w-12 h-12',
		iconContainer: 'w-16 h-16 mb-3',
		title: 'text-base',
		description: 'text-sm',
		button: 'px-3 py-1.5 text-sm',
		buttonGap: 'gap-2',
	},
	md: {
		container: 'py-12 px-6',
		icon: 'w-16 h-16',
		iconContainer: 'w-24 h-24 mb-4',
		title: 'text-lg',
		description: 'text-sm',
		button: 'px-4 py-2 text-sm',
		buttonGap: 'gap-3',
	},
	lg: {
		container: 'py-16 px-8',
		icon: 'w-20 h-20',
		iconContainer: 'w-32 h-32 mb-6',
		title: 'text-2xl',
		description: 'text-base',
		button: 'px-6 py-2.5 text-base',
		buttonGap: 'gap-4',
	},
};

export const buttonVariants = {
	primary: 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm',
	secondary: 'bg-gray-100 hover:bg-gray-200 text-gray-700',
	outline:
		'border-2 border-gray-300 hover:border-gray-400 text-gray-700 bg-white',
};
